baseURL = "http://example.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "My New Hugo Site"
theme = "beautifulhugo"

pygmentsUseClassic = false
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[languages]
    [languages.en]
    weight = 1

    [languages.it]
    weight = 2

[params]
    custom_css = ["css/mymain.css", "css/mycodeblock.css"]

    useHLJS = false

